- .github/workflows/close.yml
- .github/workflows/main.yml
- .github/workflows/pull-request.yml
- .github/workflows/push-commit.yml
- Dockerfile
- CD
- Add deploying step in `main.yml` and `pull-request.yml` to deploy container to local
- Remove building docker image in `push-commit`
- Add `close.yml` to close container in local when pull request closed
- There should add health check
> [CLUST-42] Add backend deploying workflow

- .github/workflows/close.yml
- Fix
- Add event number in close workflow
> Fix close workflow

- .github/workflows/close.yml
> Fix typo in close workflow 

- .github/workflows/main.yml
- .github/workflows/pull-request.yml
- CI
- Change platform to arm64 due to new machine
> [CLUST-48] Change platform to image

- config.example.yaml
- internal/user/service.go
- Fix
- Replace empty string values in `studentID` to `NULL`
> Fix user schema unique issue

- internal/database/migrations/202504252040_users.up.sql
- Fix
- Remove username entry in user table migration to reflect the schema change.
> Remove username entry in user table migration

- cmd/backend/main.go
- Chore
- Replace `summer-example-dev` with `clustron-backend` so that tracing can correctly identify the source
> Update default application name in main function

- internal/jwt/service.go
- Fix
- Change to directly getting user from JWT
> Fix JWT logic about getting user

- internal/setting/handler.go
- Fix
- Fix type in PublickKeyResponse json tag.
> Fix type in PublickKeyResponse json tag

- cmd/backend/main.go
- config.example.yaml
- internal/config/config.go
- internal/user/queries.sql
- internal/user/queries.sql.go
- internal/user/service.go
- Feature
- Add `PresetUser` to config for setting user role when created
> [CLUST-51] Configure admin and organizer users

- cmd/backend/main.go
- internal/auth/handler.go
- internal/database/full_schema.sql
- internal/jwt/queries.sql
- internal/jwt/queries.sql.go
- internal/jwt/service.go
- sqlc.yaml
- Feature
- Add logout API endpoint
- Inactive the refresh token when the user logout
- Clear the client-side cookie that stores access and refreshes token
- Relative API spec [clustron-api PR#7](https://github.com/NYCU-SDC/clustron-api/pull/7)
> Add logout API endpoint

- internal/membership/handler.go
- internal/membership/service.go
- Fix
- Fix error handling in the memberships handler.
> [CLUST-40] Fix memberships error

- internal/group/handler.go
- Refactor
- Get `add member request` schema from membership
> Change create group request schema

- .github/workflows/stage.yml
- CI
- Add stage deploying workflow
> Add CI workflow deploying stage version

- internal/setting/service.go
- Fix
- Get ldap user info with linux username when adding public key
> Get ldap user info with linux username

- internal/database/migrations/202506151626_rename_role_to_rolename.down.sql
- internal/database/migrations/202506151626_rename_role_to_rolename.up.sql
- internal/group/handler.go
- internal/group/handler_test.go
- internal/group/queries.sql
- internal/group/service.go
- internal/grouprole/queries.sql
- internal/grouprole/schema.sql
- internal/grouprole/service.go
- internal/grouprole/type.go
- internal/membership/handler.go
- internal/membership/queries.sql
- internal/membership/service.go
- test/testdata/database/grouprole.go
Reverts NYCU-SDC/clustron-backend#52
> Revert "[BREAKING CHANGE] [CLUST-59] Rename 'role' to 'roleName'"

- internal/ldap/client.go
- internal/setting/service.go
- Feature
- Delete public key in LDAP when a user deleting the public key in setting
> [CLUST-93] Integrate ldap remove publickey

- internal/setting/handler.go
- internal/setting/handler_test.go
- Fix
- Rename username to fullName in the onboarding request.
> Rename username to fullName in onboarding request

- go.mod
- go.sum
- internal/config/config.go
- internal/cors/middleware.go
- Chore
- Upgrade summer to the latest version to optimize the log caller path
- Enable IDE to recognize the file path in the log to trigger the Automatic jump
> Upgrade summer to the latest version to optimize the log caller path

- internal/membership/handler.go
- internal/membership/service.go
- internal/membership/type.go
- Fix
- Rename username to fullName in some leftover parts to fit API spec
> Rename username to fullName in some leftover parts

- .deploy/dev/compose.yaml
- .deploy/stage/compose.yaml
- Fix 
- Resolve traces are not being collected.
Add the otel-collector-url to fix the issue.
> fix: add otel-collector-orl for tempo

- internal/group/handler.go
- internal/membership/handler.go
- internal/membership/type.go
- Feature
- Return the status (successfully added or not) of members when creating group and adding members
- Let frontend be able to tell the user whether a member is successfully added into the group without checking the member list by their own
> [CLUST-94] Create add member error list

- cmd/backend/main.go
- internal/setting/handler.go
- internal/setting/handler_test.go
- internal/setting/queries.sql
- internal/setting/service.go
- internal/user/queries.sql
- internal/user/service.go
- Feature
- Add `boundLoginMethods` field in the setting response to get all bound login methods of a user.
> [CLUST-151] Get bound login method endpoint

- .github/workflows/pull-request.yml
- Fix
- Add `component` field to deploy metadata
> Add component metadata to pull request workflow

- .deploy/snapshot/compose.yaml
- .deploy/snapshot/deploy.sh
- .deploy/snapshot/ldif/setup.ldif
- .github/workflows/pull-request.yml
- Fix
- Add compose file and setup file to snapshot version
- Revise `environment` in payload in deploy workflow
> Revise snapshot deploy workflow

- .deploy/dev/compose.yaml
- .deploy/snapshot/compose.yaml
- .deploy/stage/compose.yaml
- .github/workflows/main.yml
- .github/workflows/pull-request.yml
- .github/workflows/stage.yml
- config.example.yaml
- internal/config/config.go
- internal/slurm/service.go
- Feature
- Add `SlurmBaseURL` to config
- Add `getNewToken` to Slurm service
- Add `SLURM_BASE_URL` to infisical
- Update GitHub action workflow
> [CLUST-171] Add getting slurm token service

- cmd/backend/main.go
- internal/auth/handler.go
- Feature
- 
- Add `/api/internal/login` for testing
> [CLUST-180] Add internal login for testing

- .deploy/dev/compose.yaml
- .deploy/snapshot/compose.yaml
- .deploy/stage/compose.yaml
- .github/workflows/main.yml
- .github/workflows/pull-request.yml
- .github/workflows/stage.yml
- cmd/backend/main.go
- config.example.yaml
- internal/config/config.go
- internal/job/handler.go
- internal/job/policy.csv
- internal/job/service.go
- internal/job/types.go
- internal/slurm/service.go
- internal/slurm/types.go
- Feature
- Add Slurm service to fetch data from Slurm RESTful
- Add a job handler to handle requests from the job form of the frontend
- Add two environment variables `slurm_restful_version` and `slurm_restful_base_url`
- Rename environment variables `slurm_base_url` to `slurm_token_help_url`
> [CLUST-176] Implement Slurm job management API and Job Form handling

- internal/job/types.go
- Fix
- Change `resource` to `resources` in slurm job response
> Revise slurm job response

- internal/config/config.go
- internal/slurm/service.go
- Fix
- Add log to provide the details of requests to slurm
> Fix slurm 404 error

- internal/grouprole/service.go
- internal/membership/handler.go
- internal/saga.go
- Fix
- Revise the logic in `AddGroupMemberHandler`
- Refactor `GetTypeByUser` in `grouprole/service.go`
> [CLUST-185] Fix the issue about adding admin himself to group

- internal/database/migrations/20251002025858_unique_user_publickey.down.sql
- internal/database/migrations/20251002025858_unique_user_publickey.up.sql
- internal/errors.go
- internal/ldap/client.go
- internal/ldap/user.go
- internal/membership/service.go
- internal/setting/queries.sql
- internal/setting/service.go
- Fix
- Add checking step before adding public key to LDAP
- 
- Adjust saga step usage in `Join` in `membership/service.go`
> [CLUST-182] Revise response when adding duplicated public key
